"""Integration tests for BaseRepository — require a real Postgres connection."""

import uuid

import pytest
from sqlalchemy.ext.asyncio import AsyncSession

from tests.support.dummy_entity import DummyEntity, DummyRepository

# Run all tests in this module on the session-scoped event loop so they share
# the asyncpg connection pool that was warmed up by _prepare_database.
pytestmark = pytest.mark.asyncio(loop_scope="session")


async def test_add_gives_entity_a_uuid_id(db_session: AsyncSession) -> None:
    repo = DummyRepository(db_session)
    entity = DummyEntity(name="alpha")

    created = await repo.add(entity)

    assert isinstance(created.id, uuid.UUID)


async def test_get_by_id_returns_entity(db_session: AsyncSession) -> None:
    repo = DummyRepository(db_session)
    entity = DummyEntity(name="beta")
    created = await repo.add(entity)

    fetched = await repo.get_by_id(created.id)

    assert fetched is not None
    assert fetched.id == created.id
    assert fetched.name == "beta"


async def test_get_by_id_returns_none_for_missing(db_session: AsyncSession) -> None:
    repo = DummyRepository(db_session)

    result = await repo.get_by_id(uuid.uuid4())

    assert result is None


async def test_list_returns_all_non_deleted(db_session: AsyncSession) -> None:
    repo = DummyRepository(db_session)
    await repo.add(DummyEntity(name="visible_a"))
    await repo.add(DummyEntity(name="visible_b"))
    hidden = DummyEntity(name="hidden")
    await repo.add(hidden)
    await repo.soft_delete(hidden)

    items = await repo.list()

    names = {e.name for e in items}
    assert "visible_a" in names
    assert "visible_b" in names
    assert "hidden" not in names


async def test_soft_delete_sets_deleted_at(db_session: AsyncSession) -> None:
    repo = DummyRepository(db_session)
    entity = DummyEntity(name="to_delete")
    await repo.add(entity)

    deleted = await repo.soft_delete(entity)

    assert deleted.deleted_at is not None


async def test_created_at_and_updated_at_set_on_insert(db_session: AsyncSession) -> None:
    repo = DummyRepository(db_session)
    entity = DummyEntity(name="timestamps")

    created = await repo.add(entity)
    await db_session.refresh(created)

    assert created.created_at is not None
    assert created.updated_at is not None


async def test_quantity_invariant_uuid_uniqueness_across_entities(
    db_session: AsyncSession,
) -> None:
    """IDs generated by the Python-side default must be unique across all instances."""
    repo = DummyRepository(db_session)

    entities = [await repo.add(DummyEntity(name=f"entity_{i}")) for i in range(10)]
    ids = [e.id for e in entities]

    assert len(ids) == len(set(ids)), "every entity must have a unique UUID"
