"""inventory_batch_transaction_tables

Revision ID: 3e51bcf30e06
Revises: 243cb5a43ba6
Create Date: 2026-06-10 20:36:51.918097

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '3e51bcf30e06'
down_revision: str | None = '243cb5a43ba6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_batches',
    sa.Column('medicine_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('batch_number', sa.String(length=100), nullable=False),
    sa.Column('manufacturing_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('quantity_available', sa.Integer(), nullable=False),
    sa.Column('quantity_reserved', sa.Integer(), nullable=False),
    sa.Column('quantity_damaged', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'quarantine', 'exhausted', 'expired', name='batch_status'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medicine_id', 'warehouse_id', 'batch_number', name='uq_batch_medicine_warehouse_number')
    )
    op.create_index(op.f('ix_inventory_batches_batch_number'), 'inventory_batches', ['batch_number'], unique=False)
    op.create_index(op.f('ix_inventory_batches_expiry_date'), 'inventory_batches', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_inventory_batches_medicine_id'), 'inventory_batches', ['medicine_id'], unique=False)
    op.create_index(op.f('ix_inventory_batches_tenant_id'), 'inventory_batches', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_inventory_batches_warehouse_id'), 'inventory_batches', ['warehouse_id'], unique=False)
    op.create_table('inventory_transactions',
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('transaction_type', sa.Enum('stock_in', 'stock_out', 'adjustment', 'return', 'damage', 'transfer', 'allocation', 'release', name='transaction_type'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['inventory_batches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_transactions_batch_id'), 'inventory_transactions', ['batch_id'], unique=False)
    op.create_index(op.f('ix_inventory_transactions_transaction_type'), 'inventory_transactions', ['transaction_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_transactions_transaction_type'), table_name='inventory_transactions')
    op.drop_index(op.f('ix_inventory_transactions_batch_id'), table_name='inventory_transactions')
    op.drop_table('inventory_transactions')
    op.drop_index(op.f('ix_inventory_batches_warehouse_id'), table_name='inventory_batches')
    op.drop_index(op.f('ix_inventory_batches_tenant_id'), table_name='inventory_batches')
    op.drop_index(op.f('ix_inventory_batches_medicine_id'), table_name='inventory_batches')
    op.drop_index(op.f('ix_inventory_batches_expiry_date'), table_name='inventory_batches')
    op.drop_index(op.f('ix_inventory_batches_batch_number'), table_name='inventory_batches')
    op.drop_table('inventory_batches')
    op.execute('DROP TYPE IF EXISTS transaction_type')
    op.execute('DROP TYPE IF EXISTS batch_status')
    # ### end Alembic commands ###
